---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: argocd-operator-helm.v0.0.3
